### ISSUE TITLE
Chrome sometimes not drawing tiles.

### ISSUE THREAD

**Issue by gregchalmers** [metoceanapi/wxtiles-leaflet#1]
I Chrome sometimes its not drawing tiles.

Errors in console

```The specified value "" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.```

Seems OK in firefox.

**Comment by gregchalmers** [comment]
[tiles.metoceanapi.com-1663018239865.log](https://github.com/metoceanapi/wxtiles-leaflet/files/9551970/tiles.metoceanapi.com-1663018239865.log)
![image (1)](https://user-images.githubusercontent.com/12605243/189762609-24376185-0900-4798-b208-e20542b0370f.png)

**Comment by gregchalmers** [comment]
Version 103.0.5060.134 (Official Build) (64-bit) is ok

**Comment by SergeiMelman** [comment]
Found and fixed an issue in demo [https://tiles.metoceanapi.com/](https://tiles.metoceanapi.com/)
Should not appear in any way in [https://www.swellmap.com/map-forecasts/](https://www.swellmap.com/map-forecasts/)
